conf/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('document_processing.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

document_processing/urls.py
from django.urls import path
from document_processing import views

app_name = 'document_processing'

urlpatterns = [
    path('textbox-processing/', views.TextboxProcessingView.as_view(), name='textbox_processing'),
    path('textbox/<int:pk>', views.TextboxView.as_view(), name='textbox'),
    path('processed-files/', views.FileProcessingView.as_view(), name='processed_file'),
    path('progress/<int:pk>', views.get_file_progress, name='get_file_progress'),
]

document_processing/models.py
from django.db import models


class File(models.Model):

    class InputTypes(models.TextChoices):
        DOCX = 'docx'
        TXT = 'txt'
        IMAGE = 'image'
        PDF = 'pdf'
        TEXTBOX = 'textbox'

    input_type = models.CharField(max_length=50, choices=InputTypes.choices, blank=True, default='')
    origin_file = models.FileField(upload_to='origins', null=True)
    origin_mime = models.CharField(max_length=120, blank=True, default='')
    origin_text = models.TextField(blank=True, default='')
    processed_text = models.TextField(blank=True, default='')
    processed_file = models.FileField(upload_to='processed', null=True)
    progress = models.PositiveSmallIntegerField(default=0)

    @property
    def short_origin_name(self):
        if self.input_type == self.InputTypes.TEXTBOX:
            return f'{self.origin_text[:50]}...'
        try:
            return self.origin_file.path.split('/')[-1]
        except ValueError:
            return ''

    @property
    def short_processed_name(self):
        if self.input_type == self.InputTypes.TEXTBOX:
            return f'{self.processed_text[:50]}...'
        try:
            return self.processed_file.path.split('/')[-1]
        except ValueError:
            return ''

document_processing/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column
from django import forms

from document_processing.models import File


class MultipleFileUploadForm(forms.ModelForm):
    origin_file = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
        required=True,
        label='Файлы'
    )

    class Meta:
        model = File
        fields = ('origin_file',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Загрузить'))

    def save(self, *args, **kwargs):
        commit = kwargs.get('commit', True)
        self.instance.origin_file, *files = self.files.getlist('origin_file')
        first_file = super().save(*args, **kwargs)
        other_files = [File(origin_file=file) for file in files]
        if commit:
            for file in other_files:
                file.save()
        return [first_file, *other_files]


class TextboxForm(forms.ModelForm):
    processed = forms.CharField(widget=forms.Textarea(attrs={'readonly': True}), required=False)

    class Meta:
        model = File
        fields = ('origin_text',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(Column('origin_text'), Column('processed')),
            Row(Submit('submit', 'Загрузить')),
        )

document_processing/views.py
import json

from django.http import HttpResponse
from django.urls import reverse
from django.views.generic import CreateView, ListView, DetailView

from document_processing.forms import MultipleFileUploadForm, TextboxForm
from document_processing.models import File
from document_processing.tasks import process_file
from text_processor import TextProcessor


class TextboxProcessingView(CreateView):
    model = File
    form_class = TextboxForm
    template_name = 'document_processing/textbox_processing.html'
    context_object_name = 'files'
    object_list = None

    def get_success_url(self):
        return reverse('document_processing:textbox', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        text_processor = TextProcessor()
        form.instance.processed_text = text_processor.process(form.cleaned_data['origin_text'])
        return super().form_valid(form)


class TextboxView(DetailView):
    model = File
    template_name = 'document_processing/textbox.html'


class FileProcessingView(CreateView, ListView):
    model = File
    form_class = MultipleFileUploadForm
    template_name = 'document_processing/file_processing.html'
    context_object_name = 'files'

    def get_success_url(self):
        return self.request.path

    def get_queryset(self):
        return File.objects.exclude(input_type=File.InputTypes.TEXTBOX).order_by('-pk')

    def form_valid(self, form):
        result = super().form_valid(form)
        for file in self.object:
            process_file(file_id=file.pk)
        return result


def get_file_progress(request, pk):
    file = File.objects.get(pk=pk)
    try:
        processed_url = file.processed_file.url
    except ValueError:
        processed_url = '#'
    return HttpResponse(json.dumps({
        'progress': file.progress,
        'processed_url': processed_url,
        'processed_name': file.short_processed_name,
    }), content_type="application/json")

document_processing/templates/document_processing/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <title>KEK-FILES</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style>
    {% block style %}{% endblock style %}
  </style>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand mr-4" href="#">KEK</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
       <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
        <ul class="navbar-nav col-10">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'document_processing:processed_file' %}">Files</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'document_processing:textbox_processing' %}">Text</a>
          </li>
        </ul>
      </div>
    </nav>


  {% block content %}{% endblock content %}


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  {% block scripts %}{% endblock scripts %}
</body>
</html>

document_processing/templates/document_processing/file_processing.html
{% extends 'document_processing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<main class="container mt-3">
    <h1>File processing</h1>
    <div>{% crispy form %}</div>
    <div>
        <table class="table">
            <thead>
            <tr>
                <th>ID</th>
                <th>Origin</th>
                <th>Processed</th>
                <th>Progress</th>
            </tr>
            </thead>
            <tbody>
            {% for file in files %}
            <tr class="processing-info" data-file-id="{{file.id}}">
                <td name="id">{{file.id}}</td>
                <td name="origin"><a href="file.origin_file.url">{{file.short_origin_name}}</a></td>
                <td name="processed"><a href="file.origin_file.url">{{file.short_processed_name}}</a></td>
                <td name="progress"><progress class="progress progress-success" value="{{file.progress}}" max="100"></progress>
    </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

</main>
{% endblock %}


{% block scripts %}
<script>
  $(document).ready(
      function() {
          $(".processing-info").each(
              function(){
                  let polling = setInterval(
                      async () => {
                          let current_value = parseInt($( this ).children('td[name="progress"]').children('progress')[0].getAttribute("value"));
                          if (current_value === 100) {
                              clearInterval(polling);
                              return;
                          }
                          let response = await fetch("/progress/" + $( this ).attr("data-file-id"));
                          if (!response.ok){
                              return;
                          }
                          let json = await response.json();
                          if (current_value < json.progress){
                              $( this ).children('td[name="progress"]').children('progress')[0].setAttribute("value", json.progress);
                              $( this ).children('td[name="processed"]').children('a')[0].setAttribute("href", json.processed_url);
                              $( this ).children('td[name="processed"]').children('a')[0].textContent = json.processed_name;
                          }


                      }, 250
                  );
              }
          );
      }
  );

</script>
{% endblock scripts %}

document_processing/templates/document_processing/load-file.html
{% extends 'document_processing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{% crispy form %}
{% endblock %}

document_processing/templates/document_processing/processed-file.html
{% extends 'document_processing/base.html' %}

{% block content %}

<div>
    {% if object.processed_text %}
        {{ object.processed_text }}
    {% else %}
        Processing... (Press F5)
    {% endif%}
</div>

{% endblock %}

document_processing/templates/document_processing/textbox.html
{% extends 'document_processing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<main class="container mt-3">
    <div class="row">
            <div class="col-md-6"><h2>Origin</h2>{{object.origin_text}}</div>
            <div class="col-md-6"><h2>Processed</h2>{{object.processed_text}}</div>
    </div>
</main>
{% endblock %}

document_processing/templates/document_processing/textbox_processing.html
{% extends 'document_processing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<main class="container mt-3">
    <h1>Text processing</h1>
    <div>{% crispy form %}</div>

</main>
{% endblock %}

document_processing/templates/document_processing/upload-files.html
{% extends 'document_processing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{% crispy form %}

{% endblock %}


{% block scripts %}
<script>
  $('#{{ form.file.id_for_label }}').on('change', function() {
      if ($(this)[0].files){
        let files_amount = $(this)[0].files.length;
        if (files_amount % 10 === 1){
            $(this).next('.custom-file-label').html('Выбран ' + files_amount + ' файл');
        } else if (files_amount % 10 === 2 || files_amount % 10 === 3 || files_amount % 10 === 4){
            $(this).next('.custom-file-label').html('Выбрано ' + files_amount + ' файла');
        } else {
            $(this).next('.custom-file-label').html('Выбрано ' + files_amount + ' файлов');
        }
      }
  });
</script>
{% endblock scripts %}